Documentation Added
OpenMined/SyferText pull request #164
Opened 2020-09-09 08:44 UTC by hershd23

## Description
Documentation of SyferText, currently linked to my localfork(branch tests) can be found here

https://syfertext.readthedocs.io/en/tests/index.html

## Affected Dependencies
The list of dependencies can be found in docs/requirements.txt

## How has this been tested?

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

2020-09-09 11:58 UTC, Nilanshrajput commented on docs/source/conf.py
> +project = "Syfertext"
```suggestion
project = "SyferText"
```

2020-09-09 12:45 UTC, Nilanshrajput commented on syfertext/tokenizer.py
> +        if prefixes:
```suggestion
        if prefixes is not None:
```

2020-09-09 12:46 UTC, Nilanshrajput commented on syfertext/tokenizer.py
> +        if suffixes:
```suggestion
        if suffixes is not None:
```

2020-09-09 12:46 UTC, Nilanshrajput commented on syfertext/tokenizer.py
> +        if infixes:
```suggestion
        if infixes is not None:
```

2020-09-09 12:47 UTC, Nilanshrajput commented on syfertext/tokenizer.py
>          if exceptions:
```suggestion
        if exceptions is not None:
```

2020-09-09 18:51 UTC, Nilanshrajput commented
Nice work, one issue is can you change the order of files and methods as they are defined not alphabetically  

`autodoc_member_order = 'bysource'` https://stackoverflow.com/questions/37209921/python-how-not-to-sort-sphinx-output-in-alphabetical-order

2020-09-10 10:08 UTC, hershd23 commented
Member order is now done by source and I have also included private and special functions. Take a look once it's built maybe we would not need all those functions to be listed. Let me know if anything has to be excluded from the docs

2020-09-10 12:35 UTC, AlanAboudib requested changes
Great work @hershd23. Two things to take into account:

- The SyferText version number should appear in the docs
- An issue should be created to proof read the docs and account for some formatting errors and typos. We can go for this as an initial version and improve it iteratively

2020-09-10 12:35 UTC, AlanAboudib commented on syfertext/tokenizer.py
> +        # To solve the defult value error in the docs
```suggestion
        # If affixes are set to None, they should take the default 
        # values
```

2020-09-10 12:44 UTC, Nilanshrajput commented
@hershd23 one thing, update the readme also, link this documentation website in readme.

2020-09-10 20:47 UTC, AlanAboudib approved these changes
Great work @hershd23

2020-09-10 20:47 UTC, merged