fix issue#1 -> change syft version
OpenMined/SyferText pull request #209
Opened 2021-04-15 20:44 UTC by FernandoDorado

## Description
The syft version for setup.py was 0.4.0, which was non-existent at https://pypi.org/project/syft/#history. That's why it has been replaced by the most recent one. 

## Affected Dependencies
syft

## How has this been tested?
- Running on Windows 10 and Linux (WSL2)

## Checklist
- [ X] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ X] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [X ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ X] My changes are covered by tests

2021-04-21 19:59 UTC, AlanAboudib requested changes

2021-04-21 19:59 UTC, AlanAboudib commented on setup.py
> +    install_requires=["tqdm==4.36.1", "mmh3==2.5.1", "requests==2.22.0", "syft==0.5.0rc1"],
This is the write version of Syft that should be installed with SyferText 

https://github.com/OpenMined/PySyft/tree/alan_syfertext_lm

2021-05-05 19:52 UTC, FernandoDorado commented
I have updated the copyright and licence files to put the correct names.

2021-05-13 11:12 UTC, FernandoDorado commented
I have done 17 tests for the spacy tokenizer as you said. For this, I have relied on the official spacy tests, and I have been able to do almost all of them. All tests have been passed. 
To execute them:

`pytest tests/tokenizer/test_spacy_tokenizer.py`

2021-05-15 09:54 UTC, AlanAboudib requested changes
One more thing ;)

2021-05-15 09:54 UTC, AlanAboudib commented on docs/conf.py
> +    ("index", "user_guide.tex", "SyferText Documentation", "Fernando Dorado", "manual")
Your name is still here as author :D

2021-05-15 12:04 UTC, AlanAboudib approved these changes

2021-05-15 16:10 UTC, AlanAboudib approved these changes

2021-05-15 16:24 UTC, AlanAboudib requested changes

2021-05-15 16:24 UTC, AlanAboudib commented on setup.cfg
> +    syft==0.3.0.post0.dev1485+g80bc24993.dirty
```suggestion
    syft
```

2021-05-15 16:24 UTC, AlanAboudib commented on setup.cfg
> +    git+https://github.com/OpenMined/PySyft.git@alan_syfertext_lm#egg=syft-0.3.0.post0.dev1485+g80bc24993.dirty
```suggestion
    git+https://github.com/OpenMined/PySyft.git@alan_syfertext_lm#egg=syft
```

2021-05-15 16:38 UTC, AlanAboudib requested changes

2021-05-15 16:38 UTC, AlanAboudib commented on setup.cfg
> +    mmh3==2.5.
```suggestion
```

2021-05-15 16:38 UTC, AlanAboudib commented on setup.cfg
> +    requests==2.22.0
```suggestion
```

2021-05-15 16:38 UTC, AlanAboudib commented on setup.cfg
> +    pytest>=5.3.5
```suggestion
```

2021-05-15 16:38 UTC, AlanAboudib commented on setup.cfg
> +    jupyter>=1.0.0
```suggestion
```

2021-05-15 16:38 UTC, AlanAboudib commented on setup.cfg
> +    papermill>=1.2.1
```suggestion
```

2021-05-15 16:38 UTC, AlanAboudib commented on setup.cfg
> +    pytest-cov
```suggestion
```

2021-05-15 16:55 UTC, AlanAboudib requested changes

2021-05-15 16:55 UTC, AlanAboudib commented on setup.cfg
> +    syft
```suggestion
    'syft-syfertext @ git+https://github.com/OpenMined/PySyft.git@alan_syfertext_lm#egg=syft-syfertext'
```

2021-05-15 16:55 UTC, AlanAboudib commented on setup.cfg
> +    git+https://github.com/OpenMined/PySyft.git@alan_syfertext_lm#egg=syft
```suggestion
```

2021-05-15 19:05 UTC, AlanAboudib requested changes

2021-05-15 19:05 UTC, AlanAboudib commented on setup.cfg
> +    'syft-syfertext @ git+https://github.com/OpenMined/PySyft.git@alan_syfertext_lm#egg=syft-syfertext'
```suggestion
    'syft_syfertext @ git+https://github.com/OpenMined/PySyft.git@alan_syfertext_lm#egg=syft_syfertext'
```

2021-05-15 19:09 UTC, AlanAboudib requested changes

2021-05-15 19:09 UTC, AlanAboudib commented on setup.cfg
> +    'syft-syfertext @ git+https://github.com/OpenMined/PySyft.git@alan_syfertext_lm#egg=syft-syfertext'
```suggestion
    'syftsyfer @ git+https://github.com/OpenMined/PySyft.git@alan_syfertext_lm#egg=syftsyfer'
```

2021-05-15 19:12 UTC, AlanAboudib requested changes

2021-05-15 19:12 UTC, AlanAboudib commented on setup.cfg
> +    'syft_syfertext @ git+https://github.com/OpenMined/PySyft.git@alan_syfertext_lm#egg=syft_syfertext'
```suggestion
    'syftsyfertext @ git+https://github.com/OpenMined/PySyft.git@alan_syfertext_lm#egg=syftsyfertext'
```

2021-05-15 19:14 UTC, AlanAboudib requested changes

2021-05-15 19:14 UTC, AlanAboudib commented on setup.cfg
> +    'syftsyfertext @ git+https://github.com/OpenMined/PySyft.git@alan_syfertext_lm#egg=syftsyfertext'
```suggestion
    syftsyfertext @ git+https://github.com/OpenMined/PySyft.git@alan_syfertext_lm#egg=syftsyfertext
```

2021-05-15 19:21 UTC, AlanAboudib requested changes

2021-05-15 19:21 UTC, AlanAboudib commented on setup.cfg
> +    syftsyfertext @ git+https://github.com/OpenMined/PySyft.git@alan_syfertext_lm#egg=syftsyfertext
```suggestion
    syft @ git+https://github.com/OpenMined/PySyft.git@alan_syfertext_lm#egg=syft
```

2021-05-18 15:35 UTC, AlanAboudib approved these changes

2021-05-18 15:57 UTC, closed without merging